
env = XCURSOR_SIZE,23
env = HYPRCURSOR_SIZE,23


#https://wiki.hypr.land/Configuring/Binds/

source = bind.conf
source = var.conf
source = input.conf
source = animation.conf
source = autostart.conf
source = windowrules.conf

#===========#
#= MONITOR =#
#===========#

#main Display
monitor = eDP-1 , 1920x1080@60 , 0x0 , 1.2

# fix xwayland
xwayland {
    force_zero_scaling = true
}

#===========#
#= AUTORUN =#
#===========#

# wallpaper
#exec-once = swww-daemon
#exec-once = hyprpaper
exec-once = swaybg -m fill -i /home/techima/.datfiles/wallpaper/bg0.jpg

# AUTOKill

exec-once = rfkill block bluetooth

#===============#
#= Curcor rule =#
#===============#

general {
    resize_on_border = true
}

