
# Main
$terminal        = kitty
$fileManager     = dolphin
$launcher        = rofi -show drun
$clipboard       = rofi -show file
$browser         = firefox

# Program
$p.telegram      = Telegram

# Mod Key 
$k.enter         = Return
$k.main          = SUPER

# Cursors
$cursor          = hyprctl setcursor Moga-Neon-Purple 28
