#===============#
#= WINDOWRULES =#
#===============#

windowrule {
  name = Happ
  match:class = Happ

  float = on
  size = 800 700
  center = on
}

windowrule {
  name = telegram
  match:class = org.telegram.desktop

  float = on
  size = 1020 600
  center = on
}

windowrule {
  name = firefox-pip
  match:class = firefox
  match:title = Picture-in-Picture

  float = on
  move = 1229 688 
  pin = true
  size = 360 200
}

windowrule {
  name = steam-friends
  match:class = steam
  match:title = Friends List

  float = on
  size = 1000 700
  center = on
}

windowrule {
    name = dolphin
    match:class = org.kde.dolphin
    
    size = 910 520
    float = on
    center = on
}

windowrule {
  name = KDENLIVE
  match:class = org.kde.kdenlive
  match:title = Splash Screen — Kdenlive

  float = on
  center = on
}

# = Bluetooth && nmGUI
windowrule {
    name = blueman
    match:class = blueman-manager

    float = on
    size = 567 361
    pin = true
}

windowrule {
  name = nm-connection-editor
  match:class = nm-connection-editor

  float = on
  size = 520 300
  pin = true
}