#=============#
#= AUTOSTART =#
#=============#

exec-once = waybar & mako & $cursor
exec-once = gnome-keyring-daemon --start --components = secrets, pkcs11, ssh, gpg

# wallpaper
#exec-once = swww-daemon
#exec-once = hyprpaper
exec-once = swaybg -m fill -i  ~/linux.conf/wallpaper/bg0.jpg

# clipboard
exec-once = wl-clip-persist --clipboard regular
exec-once = wl-paste --type text    --watch cliphist store  
exec-once = wl-paste --type image   --watch cliphist store

#= Kill autostart

exec-once = pkill blueman-applet
exec-once = rfkill block bluetooth

